module.exports = {
  presets: ["module:metro-react-native-babel-preset"],
  plugins: [
    [
      "module-resolver",
      {
        root: ["./src"],
        extensions: [
          ".ios.ts",
          ".android.ts",
          ".ts",
          ".ios.tsx",
          ".android.tsx",
          ".tsx",
          ".jsx",
          ".js",
          ".json",
        ],
        alias: {
          "@": "./src",
          "@component": "./src/app/component",
          "@type": "./src/app/type",
          "@util": "./src/app/util",
          "@navigation": "./src/app/navigation",
          "@hooks": "./src/app/hooks",
          "@screen": "./src/app/screen",
          "@enum": "./src/app/enum",
          "@store": "./src/app/store",
          "@asyncStorage": "./src/app/asyncStorage",
          "@encrytedStorage": "./src/app/encrytedStorage",
          "@assets": "./src/assets",
          "@fonts": "./src/assets/fonts",
          "@images": "./src/assets/images",
          "@styles": "./src/styles",
          "@translations": "./src/translations",
          "@api": "./src/api",
          "@queries": "./src/queries",
        },
      },
      "babel-plugin-styled-components",
    ],
    "@babel/plugin-transform-template-literals",
    "@babel/plugin-proposal-nullish-coalescing-operator",
    "@babel/plugin-proposal-optional-chaining",
    "@babel/plugin-transform-arrow-functions",
    "react-native-reanimated/plugin",
  ],
};
